# CMake generated Testfile for 
# Source directory: C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests
# Build directory: C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/backend/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[message_codec_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/Debug/message_codec_test.exe")
  set_tests_properties([=[message_codec_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;5;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[message_codec_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/Release/message_codec_test.exe")
  set_tests_properties([=[message_codec_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;5;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[message_codec_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/MinSizeRel/message_codec_test.exe")
  set_tests_properties([=[message_codec_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;5;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[message_codec_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/RelWithDebInfo/message_codec_test.exe")
  set_tests_properties([=[message_codec_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;5;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[message_codec_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[message_bus_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/Debug/message_bus_test.exe")
  set_tests_properties([=[message_bus_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;10;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[message_bus_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/Release/message_bus_test.exe")
  set_tests_properties([=[message_bus_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;10;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[message_bus_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/MinSizeRel/message_bus_test.exe")
  set_tests_properties([=[message_bus_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;10;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[message_bus_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/RelWithDebInfo/message_bus_test.exe")
  set_tests_properties([=[message_bus_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;10;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[message_bus_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[order_flow_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/Debug/order_flow_test.exe")
  set_tests_properties([=[order_flow_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;15;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[order_flow_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/Release/order_flow_test.exe")
  set_tests_properties([=[order_flow_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;15;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[order_flow_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/MinSizeRel/order_flow_test.exe")
  set_tests_properties([=[order_flow_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;15;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[order_flow_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/RelWithDebInfo/order_flow_test.exe")
  set_tests_properties([=[order_flow_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;15;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[order_flow_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[data_writer_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/Debug/data_writer_test.exe")
  set_tests_properties([=[data_writer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;20;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[data_writer_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/Release/data_writer_test.exe")
  set_tests_properties([=[data_writer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;20;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[data_writer_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/MinSizeRel/data_writer_test.exe")
  set_tests_properties([=[data_writer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;20;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[data_writer_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/RelWithDebInfo/data_writer_test.exe")
  set_tests_properties([=[data_writer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;20;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[data_writer_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[api_gateway_contract_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/Debug/api_gateway_contract_test.exe")
  set_tests_properties([=[api_gateway_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;25;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[api_gateway_contract_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/Release/api_gateway_contract_test.exe")
  set_tests_properties([=[api_gateway_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;25;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[api_gateway_contract_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/MinSizeRel/api_gateway_contract_test.exe")
  set_tests_properties([=[api_gateway_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;25;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[api_gateway_contract_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/RelWithDebInfo/api_gateway_contract_test.exe")
  set_tests_properties([=[api_gateway_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;25;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[api_gateway_contract_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[api_order_guard_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/Debug/api_order_guard_test.exe")
  set_tests_properties([=[api_order_guard_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;30;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[api_order_guard_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/Release/api_order_guard_test.exe")
  set_tests_properties([=[api_order_guard_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;30;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[api_order_guard_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/MinSizeRel/api_order_guard_test.exe")
  set_tests_properties([=[api_order_guard_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;30;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[api_order_guard_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/RelWithDebInfo/api_order_guard_test.exe")
  set_tests_properties([=[api_order_guard_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;30;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[api_order_guard_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[api_network_e2e_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/Debug/api_network_e2e_test.exe")
  set_tests_properties([=[api_network_e2e_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;46;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[api_network_e2e_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/Release/api_network_e2e_test.exe")
  set_tests_properties([=[api_network_e2e_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;46;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[api_network_e2e_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/MinSizeRel/api_network_e2e_test.exe")
  set_tests_properties([=[api_network_e2e_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;46;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[api_network_e2e_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-codex/bin/RelWithDebInfo/api_network_e2e_test.exe")
  set_tests_properties([=[api_network_e2e_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;46;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[api_network_e2e_test]=] NOT_AVAILABLE)
endif()
