# CMake generated Testfile for 
# Source directory: C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests
# Build directory: C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/backend/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[message_codec_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Debug/message_codec_test.exe")
  set_tests_properties([=[message_codec_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;5;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[message_codec_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Release/message_codec_test.exe")
  set_tests_properties([=[message_codec_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;5;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[message_codec_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/MinSizeRel/message_codec_test.exe")
  set_tests_properties([=[message_codec_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;5;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[message_codec_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/RelWithDebInfo/message_codec_test.exe")
  set_tests_properties([=[message_codec_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;5;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[message_codec_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[message_bus_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Debug/message_bus_test.exe")
  set_tests_properties([=[message_bus_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;10;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[message_bus_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Release/message_bus_test.exe")
  set_tests_properties([=[message_bus_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;10;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[message_bus_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/MinSizeRel/message_bus_test.exe")
  set_tests_properties([=[message_bus_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;10;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[message_bus_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/RelWithDebInfo/message_bus_test.exe")
  set_tests_properties([=[message_bus_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;10;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[message_bus_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[order_flow_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Debug/order_flow_test.exe")
  set_tests_properties([=[order_flow_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;15;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[order_flow_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Release/order_flow_test.exe")
  set_tests_properties([=[order_flow_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;15;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[order_flow_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/MinSizeRel/order_flow_test.exe")
  set_tests_properties([=[order_flow_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;15;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[order_flow_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/RelWithDebInfo/order_flow_test.exe")
  set_tests_properties([=[order_flow_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;15;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[order_flow_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[order_tif_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Debug/order_tif_test.exe")
  set_tests_properties([=[order_tif_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;20;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[order_tif_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Release/order_tif_test.exe")
  set_tests_properties([=[order_tif_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;20;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[order_tif_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/MinSizeRel/order_tif_test.exe")
  set_tests_properties([=[order_tif_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;20;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[order_tif_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/RelWithDebInfo/order_tif_test.exe")
  set_tests_properties([=[order_tif_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;20;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[order_tif_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[order_concurrency_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Debug/order_concurrency_test.exe")
  set_tests_properties([=[order_concurrency_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;25;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[order_concurrency_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Release/order_concurrency_test.exe")
  set_tests_properties([=[order_concurrency_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;25;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[order_concurrency_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/MinSizeRel/order_concurrency_test.exe")
  set_tests_properties([=[order_concurrency_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;25;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[order_concurrency_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/RelWithDebInfo/order_concurrency_test.exe")
  set_tests_properties([=[order_concurrency_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;25;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[order_concurrency_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[risk_reservation_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Debug/risk_reservation_test.exe")
  set_tests_properties([=[risk_reservation_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;30;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[risk_reservation_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Release/risk_reservation_test.exe")
  set_tests_properties([=[risk_reservation_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;30;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[risk_reservation_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/MinSizeRel/risk_reservation_test.exe")
  set_tests_properties([=[risk_reservation_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;30;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[risk_reservation_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/RelWithDebInfo/risk_reservation_test.exe")
  set_tests_properties([=[risk_reservation_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;30;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[risk_reservation_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[data_writer_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Debug/data_writer_test.exe")
  set_tests_properties([=[data_writer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;35;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[data_writer_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Release/data_writer_test.exe")
  set_tests_properties([=[data_writer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;35;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[data_writer_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/MinSizeRel/data_writer_test.exe")
  set_tests_properties([=[data_writer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;35;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[data_writer_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/RelWithDebInfo/data_writer_test.exe")
  set_tests_properties([=[data_writer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;35;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[data_writer_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[api_gateway_contract_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Debug/api_gateway_contract_test.exe")
  set_tests_properties([=[api_gateway_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;40;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[api_gateway_contract_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Release/api_gateway_contract_test.exe")
  set_tests_properties([=[api_gateway_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;40;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[api_gateway_contract_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/MinSizeRel/api_gateway_contract_test.exe")
  set_tests_properties([=[api_gateway_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;40;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[api_gateway_contract_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/RelWithDebInfo/api_gateway_contract_test.exe")
  set_tests_properties([=[api_gateway_contract_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;40;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[api_gateway_contract_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[api_order_guard_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Debug/api_order_guard_test.exe")
  set_tests_properties([=[api_order_guard_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;45;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[api_order_guard_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Release/api_order_guard_test.exe")
  set_tests_properties([=[api_order_guard_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;45;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[api_order_guard_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/MinSizeRel/api_order_guard_test.exe")
  set_tests_properties([=[api_order_guard_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;45;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[api_order_guard_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/RelWithDebInfo/api_order_guard_test.exe")
  set_tests_properties([=[api_order_guard_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;45;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[api_order_guard_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[api_network_e2e_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Debug/api_network_e2e_test.exe")
  set_tests_properties([=[api_network_e2e_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;61;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[api_network_e2e_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Release/api_network_e2e_test.exe")
  set_tests_properties([=[api_network_e2e_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;61;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[api_network_e2e_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/MinSizeRel/api_network_e2e_test.exe")
  set_tests_properties([=[api_network_e2e_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;61;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[api_network_e2e_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/RelWithDebInfo/api_network_e2e_test.exe")
  set_tests_properties([=[api_network_e2e_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;61;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[api_network_e2e_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[event_journal_replay_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Debug/event_journal_replay_test.exe")
  set_tests_properties([=[event_journal_replay_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;74;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[event_journal_replay_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Release/event_journal_replay_test.exe")
  set_tests_properties([=[event_journal_replay_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;74;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[event_journal_replay_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/MinSizeRel/event_journal_replay_test.exe")
  set_tests_properties([=[event_journal_replay_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;74;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[event_journal_replay_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/RelWithDebInfo/event_journal_replay_test.exe")
  set_tests_properties([=[event_journal_replay_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;74;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[event_journal_replay_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[fix_adapter_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Debug/fix_adapter_test.exe")
  set_tests_properties([=[fix_adapter_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;82;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[fix_adapter_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Release/fix_adapter_test.exe")
  set_tests_properties([=[fix_adapter_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;82;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[fix_adapter_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/MinSizeRel/fix_adapter_test.exe")
  set_tests_properties([=[fix_adapter_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;82;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[fix_adapter_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/RelWithDebInfo/fix_adapter_test.exe")
  set_tests_properties([=[fix_adapter_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;82;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[fix_adapter_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[smart_router_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Debug/smart_router_test.exe")
  set_tests_properties([=[smart_router_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;86;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[smart_router_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Release/smart_router_test.exe")
  set_tests_properties([=[smart_router_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;86;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[smart_router_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/MinSizeRel/smart_router_test.exe")
  set_tests_properties([=[smart_router_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;86;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[smart_router_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/RelWithDebInfo/smart_router_test.exe")
  set_tests_properties([=[smart_router_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;86;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[smart_router_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[market_simulator_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Debug/market_simulator_test.exe")
  set_tests_properties([=[market_simulator_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;90;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[market_simulator_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/Release/market_simulator_test.exe")
  set_tests_properties([=[market_simulator_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;90;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[market_simulator_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/MinSizeRel/market_simulator_test.exe")
  set_tests_properties([=[market_simulator_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;90;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[market_simulator_test]=] "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/build-phase23/bin/RelWithDebInfo/market_simulator_test.exe")
  set_tests_properties([=[market_simulator_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;90;add_test;C:/Users/User/OneDrive/Desktop/Foreign-Exchange/backend/tests/CMakeLists.txt;0;")
else()
  add_test([=[market_simulator_test]=] NOT_AVAILABLE)
endif()
